# Generated by Django 4.2.1 on 2023-05-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('pno', models.CharField(max_length=50, verbose_name='pno')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('yop', models.CharField(max_length=50, verbose_name='Year of Pass')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('dob', models.CharField(max_length=50, verbose_name='dob')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='dob',
            field=models.CharField(max_length=50, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.CharField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pno',
            field=models.CharField(max_length=50, verbose_name='pno'),
        ),
    ]
